# Generated by Django 4.1.4 on 2023-02-08 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_buyer_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Buyer',
        ),
    ]
